spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:postgresql://db:5432/${POSTGRES_DB}
        username: postgres
        password: mysecretpassword
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

    sql:
        init:
            mode: always
