spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/garmindb
        username: postgres
        password: mysecretpassword
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            mode: always
