
spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/skminfotech
        driverClassName: org.postgresql.Driver
        username: skminfotech
        password: pass
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
    sql:
        init:
            mode: always
eureka:
    instance:
        preferIpAddress: true
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
info:
    app:
        name: "trackgarmin"
        version: "1.0.0"
